name: Validacao Tecnica LaunchLab
on: [push] # Executa o teste toda vez que a célula der 'git push'

jobs:
  testes-logica:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar Codigo da Celula
      uses: actions/checkout@v4

    - name: Configurar Ambiente Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # CASO DE TESTE 1: Solicitante com bom score e parcela dentro do limite
    - name: Testar Cliente Aprovado com Score Social Calculado
      run: |
        OUTPUT=$(echo -e "0\n2000\n1000\n0\ns\n24\n500" | python src/triagem.py)
        if [[ "$OUTPUT" =~ "Resultado: Aprovado" ]]; then
          echo "✅ Teste 1 Passou!"
        else
          echo "❌ Teste 1 Falhou: Cliente com score social alto e parcela viavel foi reprovado."
          exit 1
        fi

    # CASO DE TESTE 2: Solicitante com score abaixo de 70 (Deve ser Reprovado)
    - name: Testar Cliente Reprovado por Baixo Score
      run: |
        OUTPUT=$(echo -e "0\n2000\n1800\n500\nn\n4\n100" | python src/triagem.py)
        if [[ "$OUTPUT" =~ "Resultado: Reprovado" ]]; then
          echo "✅ Teste 2 Passou!"
        else
          echo "❌ Teste 2 Falhou: Cliente com baixo score social nao foi reprovado."
          exit 1
        fi

    # CASO DE TESTE 3: Solicitante com bom score, mas parcela acima do limite de 30%
    - name: Testar Cliente Reprovado por Comprometimento Excessivo
      run: |
        OUTPUT=$(echo -e "0\n2000\n1000\n0\ns\n24\n700" | python src/triagem.py)
        if [[ "$OUTPUT" =~ "Resultado: Reprovado" ]]; then
          echo "✅ Teste 3 Passou!"
        else
          echo "❌ Teste 3 Falhou: Parcela acima de 30% da renda foi aprovada."
          exit 1
        fi
